# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiMain.ui'
#
# Created: Sun Nov 26 20:51:18 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 400)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.CentralWidget = QtGui.QWidget(MainWindow)
        self.CentralWidget.setMinimumSize(QtCore.QSize(400, 400))
        self.CentralWidget.setObjectName("CentralWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.CentralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GridLayout = QtGui.QGridLayout()
        self.GridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.GridLayout.setSpacing(8)
        self.GridLayout.setObjectName("GridLayout")
        self.ImageLabel = QtGui.QLabel(self.CentralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageLabel.sizePolicy().hasHeightForWidth())
        self.ImageLabel.setSizePolicy(sizePolicy)
        self.ImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ImageLabel.setObjectName("ImageLabel")
        self.GridLayout.addWidget(self.ImageLabel, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.ToolButton = QtGui.QPushButton(self.CentralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToolButton.sizePolicy().hasHeightForWidth())
        self.ToolButton.setSizePolicy(sizePolicy)
        self.ToolButton.setMinimumSize(QtCore.QSize(24, 24))
        self.ToolButton.setMaximumSize(QtCore.QSize(24, 24))
        self.ToolButton.setText("")
        self.ToolButton.setObjectName("ToolButton")
        self.horizontalLayout_3.addWidget(self.ToolButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.GuessLabel = QtGui.QLabel(self.CentralWidget)
        self.GuessLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.GuessLabel.setObjectName("GuessLabel")
        self.verticalLayout_2.addWidget(self.GuessLabel)
        self.GuessText = QtGui.QLabel(self.CentralWidget)
        self.GuessText.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.GuessText.setObjectName("GuessText")
        self.verticalLayout_2.addWidget(self.GuessText)
        self.GridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.GridLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ProverbLabel = QtGui.QLabel(self.CentralWidget)
        self.ProverbLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.ProverbLabel.setMargin(0)
        self.ProverbLabel.setIndent(-1)
        self.ProverbLabel.setObjectName("ProverbLabel")
        self.verticalLayout_3.addWidget(self.ProverbLabel)
        self.ProverbText = QtGui.QLabel(self.CentralWidget)
        self.ProverbText.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ProverbText.setObjectName("ProverbText")
        self.verticalLayout_3.addWidget(self.ProverbText)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PlayerInput = QtGui.QLineEdit(self.CentralWidget)
        self.PlayerInput.setInputMask("")
        self.PlayerInput.setObjectName("PlayerInput")
        self.horizontalLayout_4.addWidget(self.PlayerInput)
        self.OkButton = QtGui.QPushButton(self.CentralWidget)
        self.OkButton.setObjectName("OkButton")
        self.horizontalLayout_4.addWidget(self.OkButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.NewGameButton = QtGui.QPushButton(self.CentralWidget)
        self.NewGameButton.setObjectName("NewGameButton")
        self.horizontalLayout.addWidget(self.NewGameButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.ExitButton = QtGui.QPushButton(self.CentralWidget)
        self.ExitButton.setObjectName("ExitButton")
        self.horizontalLayout.addWidget(self.ExitButton)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem8 = QtGui.QSpacerItem(20, 4, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem8)
        MainWindow.setCentralWidget(self.CentralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.ImageLabel.setText(QtGui.QApplication.translate("MainWindow", "ImageLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.GuessLabel.setText(QtGui.QApplication.translate("MainWindow", "GuessLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.GuessText.setText(QtGui.QApplication.translate("MainWindow", "GuessText", None, QtGui.QApplication.UnicodeUTF8))
        self.ProverbLabel.setText(QtGui.QApplication.translate("MainWindow", "ProverbLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.ProverbText.setText(QtGui.QApplication.translate("MainWindow", "ProverbText", None, QtGui.QApplication.UnicodeUTF8))
        self.OkButton.setText(QtGui.QApplication.translate("MainWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.NewGameButton.setText(QtGui.QApplication.translate("MainWindow", "New Game", None, QtGui.QApplication.UnicodeUTF8))
        self.ExitButton.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

